version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8000"  # Tu accèdes à ton backend sur http://localhost:8080
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:3000"  # Pour React (Vite), on utilise souvent 5173
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybank
    ports:
      - "3307:3306"  # Accès à la base de données via localhost:3307
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
